part 1
ValyMihalchuk/PlacerIntelligent pull request #1
Opened 2022-10-11 16:38 UTC by ValyMihalchuk

2022-10-12 20:16 UTC, AS2 requested changes
Added review

2022-10-12 20:16 UTC, AS2 commented on README.md
> +- Один предмет не может присутствовать на фото несколько раз
Есть пара вопросов, касательно выбора предметов:
1) Правильно ли я понимаю, что на вход Вашему алгоритму можно подавать произвольные предметы, а не только из Вашей выборки? Если ответ "да", то тогда, как мне кажется, резонно задаться и следующими вопросами:
1.1) Могут ли быть поданы на вход прозрачные предметы или предметы, чей цвет/текстура схож с фоном? Не будет ли проблем с корректным распознаванием предметов на фотографии?
1.2) Могут ли быть корректно распознаны предметы, обладающие различными "световыми" свойствами: как частный случай, светящиеся объекты. К примеру, включенная лампочка, может своим свечением затруднять процесс распознавания этой самой лампочки.
1.3) Тут больше не вопрос, а просто комментарий: почему нельзя использовать один предмет множество раз? Как мне кажется, этот требование имеет смысл тогда и только тогда, когда Вы разрешаете использовать предметы только из Вашей выборки. Два этих требования просто формируют тот факт, что на входной фотографии может быть конечное число предметов. Само же по себе это требование ничего не меняет.

2022-10-12 20:16 UTC, AS2 commented on README.md
> +
Как мне кажется, Ваши сформированные требования к фотографиям создают достаточно сильную вариативность возможных входных данных. Потому возникает каскад вопросов к самим входным данным, а именно:
1) Правильно ли я понимаю, что Ваш алгоритм способен работать с прочими перспективными искажениями, например, как "Рыбий глаз", который присутствует в экшн-камерах?
2) Правильно ли будут распознаваться объекты, сделанные при "неестественном" освещении (например, сделанные в ярко желтом освещении, в котором бы, как мне кажется, ободок Вашего "евро" и паркет могли бы стать более схожими и, как результат, граница между фоном и объектами могла бы "теряться").
3) Еще немного, касательно освещения: вот, к примеру, на некоторых ваших фотографиях на Евро присутствуют блики: достаточно небольшие, но все таки они появляются. Отсюда вопрос: корректно ли будет работать распознавание объектов, если освещением могут создаваться артефакты, подобные яркому блику? Как и в случае, описанным с включенной лампочкой, не может ли случиться такое, что блик будет засвечивать контур объекта, мешая тем самым точно распознать объект?
4) И еще немного про свет: Вы ничего не указали про тени, но если, к примеру, взять достаточно высокий угол между источником света и нормалью к поверхности, то тогда предметы могут отбрасывать большую тень, которая может также мешать точно определять объекты и, как следствие, алгоритм не сможет точно определить размеры объекта и выдать точный ответ на выход. Учитывает ли при работе это Ваш алгоритм?

Если при каких-то условиях Ваш алгоритм будет выдавать неправильный результат, то стоит указать соответствующие ограничения для этих условий (или подумать над тем, как оптимизировать алгоритм).

К тому же еще вот вопрос: чем принципиально отличается работа Вашего алгоритма, к примеру, с png форматом от указанного Вами jpg форматом изображений? Разве существующие библиотеки не могут работать с целым разнообразием достаточно популярных форматов? Просто мне показалось, что данное ограничение может быть немного неуместным при правильном выборе пакета для открытия файлов.

2022-10-12 20:16 UTC, AS2 commented on README.md
> +
Есть пара вопросов к требованиям к многоугольнику:
1) Может ли быть многоугольник закрашен цветом маркера? По факту, он же останется замкнутым и выпуклым, как Вы и указали.
2) Не совсем понятно, как в рамках алгоритма понимается понятие "четко": есть ли какая то минимальная граница толщины линии? Отсутствие этого требования может сформировать к примеру такую ситуацию: я подаю на вход Вашему алгоритму фотографию, сделанную с большой высоты над поверхностью, при этом линия сделана достаточно тонким маркером. Могу предположить, что в таком случае могут возникнуть трудности в процессе распознавания многоугольника.

2022-10-12 20:16 UTC, AS2 commented on README.md
> +
Есть также вопросы про требования к поверхности:
Правда ли, что Ваш алгоритм может работать с любыми поверхностями? Например, если это будет какая то шершавая поверхность с текстурой дерева, где шершавость создает ряд артефактов? Или, побоюсь представить такое, светящаяся поверхность, чей свет мешает распознать сам объекты? Или белая, как цвет листа (может там просто не сработает процесс определения границы листа, так как лист будет сливаться с фоном)?

2022-10-12 20:16 UTC, AS2 commented on README.md
> +    * лист  — максимальная по площади компонента связности[^0]
В силу Ваших требований к предметам, предметы, поступающие на вход, могут быть любыми. В частности, они могут быть больше, чем лист бумаги. Тогда тут Ваш алгоритм может выделить как самую большую компоненту связности не лист, а просто самый большой объект и, дальше, все может пойти неправильно(.
Более того, возможно стоит добавить требования к фотографии, чтобы избавиться от возможных шумов, про которые Вы писали далее?

2022-10-12 20:16 UTC, AS2 commented on README.md
> +       * Вместо ограничивающего прямоугольника можно использовать многоугольник (skimage.measure.find_contours)
Вот также есть нюанс: по идее, bound-box'ы (или даже ограничение предметов многоугольниками), которые Вы собираетесь использовать, не могут содержать в себе "дырок". Однако, не трудно представить ситуацию, когда Вы пытаетесь разместить в многоугольник, размером с ножницы, сами ножницы и предмет, который может поместиться в проекции в дырку для пальца в ножницах. Получается, что в теории ответ то правильный True, но так как баунд-бокс не учитывает дырку в ножницах, то ответ будет недостоверный...

2022-10-12 20:16 UTC, AS2 commented on README.md
> +    * Один из вариантов - использовать **жадный алгоритм** - возьмем прямоугольник с самой большой площадью и поместим его внутрь многоугольника (логичнее поместить его к границам). Проверяем, помест
Это не претензия, а больше комментарий на размышление. Насчет "размещения к границам": признаться честно, я не уверен, что нет ситуации, когда стратегия "поместить к границе" не является оптимальной, но я могу быть и не прав, поскольку вспомнить головоломки с таким раскладом не могу вспомнить. Вот тут отчасти почти та ситуация, про которую я говорю: https://www.youtube.com/watch?v=9CkpeG76t5I. Вроде как черный квадратик лежит не у границы, но один из правильных раскладов размещения такой (хотя черный квадратик наименьший из фигур). Может быть существует пример, где самая большая фигура оптимальнее всего должна находиться не у края, а где то в середине.

2022-10-12 20:16 UTC, AS2 commented on README.md
> +[^0]: в некоторых случаях, бинаризация может сработать плохо: вместо одного только листа по максимальной площади может определиться лист+шумы или что-то совсем другое. Возможно, стоит включить сюда д
Думаю, не стоит писать открытые вопросы к конечному пользователю на главную страницу программы. Предлагаю Вам избавить конечного читателя от чтения Ваших мысленных экспериментов и оставить более уместную информацию о процессе работы.  Что касается самих мыслей: действительно Вы абсолютно правы, что задумываетесь об этом. Думаю, Вам стоит попробовать провести эксперименты с разными поверхностями и линиями, и, по необходимости, можете добавить некоторые требования к фотографиям, чтобы исключить возможность некорректной работы программы.

2022-10-12 20:16 UTC, AS2 commented on README.md
> +    * находим компоненты связности предметов с помощью сортировки по площадям компонент связности[^3]
Думаю, что такую операцию, как сортировку по площади компонентам связности, будет корректно использовать только при отсутствии перспективных искажений. Иначе, если присутствует, к примеру, искажение в виде "Рыбьего глаза", то размер на фотографии может не соответствовать реальному размеру (да и не только размеру, но и габаритам) предмета. Это кстати наверно самое важное условие работы основной части Вашего алгоритма, а именно размещения масок (или баунд-боксов)  объектов: наличие перспективных искажений ведет к генерации искаженных масок и (или баунд-боксов), которые будет некорректно "помещать"  в многоугольник, используя обычные преобразования в виде поворотов и сдвигов.

2022-10-12 20:16 UTC, AS2 commented on README.md
> +[^3]: если разрешить алгоритму использовать изображения предметов, то мы будем знать их минимальный и максимальный размер относительно листа А4.
К этим трем пунктам комментарий, аналогичный предыдущему.

2022-10-12 20:16 UTC, AS2 commented on tests/description.txt
> +Проверка что маленький предмет помещается в длинный многоугольник
Здесь Ваш многоугольник имеет разрыв в лево-верхнем угле

2022-10-12 20:16 UTC, AS2 commented on README.md
> +[^0]: в некоторых случаях, бинаризация может сработать плохо: вместо одного только листа по максимальной площади может определиться лист+шумы или что-то совсем другое. Возможно, стоит включить сюда д
Хотелось бы Вас предупредить, что требование к однозначному взаимному расположению листа и предметов может быть засчитано как упрощение задачи (это не угроза если что)), просто на личном опыте знаю). Предлагаю Вам подумать о том, как можно было бы отличить компоненту связности листа (или многоугольника) от других предметов на основе, например, информации с самой входной фотографии, а не руководствуясь лишь только результатами морфологических операций? Может попробовать как то выделить многоугольник и лист, учитывая, к примеру, цвет точек объекта, выделяемого бинаризацией? Можете конечно поразмыслить и придумать какой то другой, более эффективный метод.

2022-10-12 20:16 UTC, AS2 commented on tests/description.txt
> +Проверка, что большой предмет и много маленьких не помещается в большой многоугольник
Кажется, в проекции канцелярский нож и кошелек наложились друг на друга. Может быть Ваши методы смогут корректно обработать такой случай, не знаю. Просто решил заострить на этом Ваше внимание.

2022-10-12 20:16 UTC, AS2 commented on tests/description.txt
> +Отсутствие прямоугольника
Могу предположить, что тень, создаваемая зарядкой, может исказить точное распознавание предмета.

2022-10-12 20:16 UTC, AS2 commented on README.md
> +       * Вместо того, чтобы находить границы, возможно целесообразнее использовать маски (и фигуры и предметов). Алгоритм будет таким же.
Еще один комментарий, по поводу применений масок: так как у Вас отсутствуют ограничения на размер входного изображения, то может возникнуть ситуация, когда на вход пришла ULTRA64K изображение, и тогда маски могут быть достаточно большого размера. Этот большой размер может быть излишним в силу элементарного наличия каких то прочих неточностей, которые могут возникать (артефакты бинаризации, создаваемые от теней и прочее). Можно попробовать сделать дополнительную оптимизацию, сжав все маски до какого-то одного, определенного Вами, размера, учитывая пропорции этих масок. Этот размер конечно же стоит будет подбирать уже после реализации алгоритма, чтобы проверять, не станет ли данная оптимизация причиной вывода неправильных ответов.

2022-10-17 21:05 UTC, ValyMihalchuk commented on README.md
> +- Один предмет не может присутствовать на фото несколько раз
Спасибо за замечание, в действительности я подразумевал предметы только из моей выборки, добавил в требования)

2022-10-17 21:06 UTC, ValyMihalchuk commented on README.md
> +
Формат .jpg был выбран исходя из двух причин: 
1. ради порядка и удобства, чтобы не поддерживать остальные многочисленные форматы;
2. цифровые зеркальные фотокамеры, цифровые камеры и телефоны Android записывают в именно в формате JPG. А исходя из смысла задачи, именно их будет использовать конечный пользователь.

По поводу перспективных искажений, освещения и теней – спасибо, добавил в требования. Что касается бликов – проблемы с небольшими бликами, как мне кажется, легко решаются средствами локальной бинаризации (добавил это уточнение в план).

2022-10-17 21:06 UTC, ValyMihalchuk commented on README.md
> +
Спасибо, уточнил, что именно я имел в виду под многоугольником и под понятием «четко видны»

2022-10-17 21:06 UTC, ValyMihalchuk commented on README.md
> +
Чтобы поверхность не сливалось с листом, отличное замечание, добавил. На счет светящейся поверхности, и что свет от этой поверхности может как-то помешать отделить предмет от поверхности – это уже все относится к фотометрическим требованиям, и, поскольку это касается дополнительного света - от этих проблем спасает требование на освещенность

2022-10-17 21:08 UTC, ValyMihalchuk commented on README.md
> +       * Вместо ограничивающего прямоугольника можно использовать многоугольник (skimage.measure.find_contours)
Хорошее замечание! Расписал более подробно, что подразумевается в данной конкретной задачи под «разместить»

2022-10-17 21:09 UTC, ValyMihalchuk commented on README.md
> +    * Один из вариантов - использовать **жадный алгоритм** - возьмем прямоугольник с самой большой площадью и поместим его внутрь многоугольника (логичнее поместить его к границам). Проверяем, помест
Данная стратегия может быть неоптимальной. Сама задача об упаковке многоугольников в прямоугольник является NP-трудной. Соответственно, имеет смысл применять некие эвристики. Такие алгоритмы не являются гарантированно точными или оптимальными, но достаточны для решения поставленной задачи. Комментарий на размышление вполне справедливый, на данный момент итоговый алгоритм в процессе доработки

2022-10-17 21:09 UTC, ValyMihalchuk commented on README.md
> +[^0]: в некоторых случаях, бинаризация может сработать плохо: вместо одного только листа по максимальной площади может определиться лист+шумы или что-то совсем другое. Возможно, стоит включить сюда д
Вот тут я с Вами вынужден не согласиться. Если исходить из того, что нужно конечному пользователю – то ему и план решения задачи не нужен, зачем ему то, как Вы хотели решать задачу? Здесь мы все-таки исходим из того, что план нужен не конечному пользователю, а нам самим, преподавателям, чтобы его оценить и однокурсникам, чтобы его отревьюить. В плане мы можем предлагать различные варианты решения проблем, и соответствующие проблемы, связанные с этими решениями. Так что мне кажется, что для текущего состояния проекта (этапа проектирования) вполне уместны и мысленные эксперименты, и открытые вопросы

2022-10-17 21:19 UTC, ValyMihalchuk commented on README.md
> +    * лист  — максимальная по площади компонента связности[^0]
Тут все-таки не любые предметы, спасибо Вашему замечанию выше)

2022-10-17 21:22 UTC, ValyMihalchuk commented on README.md
> +    * находим компоненты связности предметов с помощью сортировки по площадям компонент связности[^3]
Тут опять же, благодаря Вашему замечанию выше, я изменил требования, теперь у фотографии не может быть существенных перспективных искажений, в силу наложенных ограничений на объектив

2022-10-17 21:23 UTC, ValyMihalchuk commented on README.md
> +[^3]: если разрешить алгоритму использовать изображения предметов, то мы будем знать их минимальный и максимальный размер относительно листа А4.
Ответил выше)

2022-10-17 21:30 UTC, ValyMihalchuk commented on tests/description.txt
> +Отсутствие прямоугольника
Да, Вы правы, тень в общем случае исказит точное распознавание границ, но в данном конкретном примере точность неважна - проверяется случай отсутствия прямоугольника

2022-10-17 22:00 UTC, ValyMihalchuk commented on tests/description.txt
> +Проверка что маленький предмет помещается в длинный многоугольник
Исправил, хотя мне кажется, что при правильных настройках бинаризации, это не повлияет на итоговую работу алгоритма. Но, формально и для точности - все ок, спасибо за замечание!

2022-10-18 13:37 UTC, ValyMihalchuk commented on README.md
> +[^0]: в некоторых случаях, бинаризация может сработать плохо: вместо одного только листа по максимальной площади может определиться лист+шумы или что-то совсем другое. Возможно, стоит включить сюда д
Спасибо за высказанные идеи! Я в итоге рассмотрел в плане преобразование Хафа, чтобы корректнее находить границы листа

2022-10-18 13:37 UTC, ValyMihalchuk commented on tests/description.txt
> +Проверка, что большой предмет и много маленьких не помещается в большой многоугольник
Все так! Исправил)

2022-10-18 13:41 UTC, ValyMihalchuk commented on README.md
> +       * Вместо того, чтобы находить границы, возможно целесообразнее использовать маски (и фигуры и предметов). Алгоритм будет таким же.
На данный момент для меня предпочтительно использование именно bound-box-ов вместо масок, но в случае, если я буду использовать маски, обязательно включу идею сжатия масок в алгоритм. Спасибо большое за идею!

2022-10-22 20:53 UTC, merged